language: node_js

services: 
  - docker

env:
  global: 
   - IBM_CLOUD_REGION: 'us-south'
   - IBM_CLOUD_API_KEY: "c927b53a-bf8e-4d68-b3e0-ac3979c7554f"
   - REGISTRY_HOSTNAME: 'de.icr.io'
   - IKS_CLUSTER: 'c3p8us7d0cj2bgr2g73g'
   - DEPLOYMENT_NAME: 'iks-test'
   - PORT: '5001'
   - Email: 'tamish.verma@tcs.com'
   - Password: 'Devops12@'


before_install: 
    - curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
    - ibmcloud login -u 'tamish.verma@tcs.com' -p 'Devops12@' -y
    - ibmcloud plugin install -f kubernetes-service
    - ibmcloud plugin install -f container-registry
  
script:
  
  - docker images
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin


# deploy:
#   provider: elasticbeanstalk
#   region: ap-south-1
#   app: "my-first-app"
#   env: "Myfirstapp-env"
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY
#   bucket_name: "elasticbeanstalk-ap-south-1-488435218657"
#   bucket_path: "docker-multi"
#   on: 
#    branch: main
before_install: 
    - curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
    - ibmcloud login -u 'tamish.verma@tcs.com' -p 'Devops12@' -y
    - ibmcloud plugin install -f kubernetes-service
    - ibmcloud plugin install -f container-registry
    - chmod +x cluster_configuration.sh

install:
    - "./cluster_configuration.sh"
    
    
       
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: main
