language: generic

services: 
  - docker
 
# script:
#   - docker build -t rtxverma123/travisexpressapp .
#   - docker images
#   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
#   - docker push rtxverma123/travisexpressapp

deploy:
  provider: elasticbeanstalk
  region: ap-south-1
  app: "my-first-app"
  env: "Myfirstapp-env"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket_name: "tamishbucket"
  bucket_path: "docker"
  on: 
   branch: main
