language: node_js

services: 
  - docker
 
script:
  - docker build -t rtxverma123/travisexpressapp .
  - docker images

deploy: 
  #edge: true
  provider: script
  script: bash docker_push
  on: 
   branch: all
