language: node_js

services: 
  - docker
 
script:
  - docker build -t rtxverma123/travisexpressapp .
  - docker images
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push rtxverma123/travisexpressapp

# deploy:
#   provider: elasticbeanstalk
#   region: ap-south-1
#   app: "my-first-app"
#   env: "Myfirstapp-env"
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY
#   bucket_name: "elasticbeanstalk-ap-south-1-488435218657"
#   bucket_path: "docker-multi"
#   on: 
#    branch: main


sudo: required

services: 
  - docker


# deploy: 
#    provider: elasticbeanstalk
#    region: ap-south-1
#    app: "myexpress-blog"
#    env: "Myexpressblog-env"
#    bucket_name: "elasticbeanstalk-ap-south-1-488435218657"
#    bucket_path: "docker"
#    access_key_id: $ACCESS
#    secret_access_key: $SECRET
#    on: 
#     branch: master
deploy: 
   IBM_CLOUD_REGION: 'us-south'
   IBM_CLOUD_API_KEY: "c927b53a-bf8e-4d68-b3e0-ac3979c7554f"
   REGISTRY_HOSTNAME: 'de.icr.io'
   IKS_CLUSTER: 'c3p8us7d0cj2bgr2g73g'
   DEPLOYMENT_NAME: 'iks-test'
   PORT: '5001'

before_install: 
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.t)/bin/linux/amd64/kubectl \
    && chmod +x ./kubectl \
    && mv ./kubectl /usr/local/bin/kubectl
  
scripts: 
    - curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
    - ibmcloud login --apikey c927b53a-bf8e-4d68-b3e0-ac3979c7554f -r "${IBM_CLOUD_REGION}" -g Default
    
    
after_install:
    - kubectl apply -f deploy.yml
    - kubectl apply -f service.yml
