
apiVersion: v1
kind: Service
metadata: 
    name: myservice
spec: 
  type: NodePort
  selector: 
      app: myapp
  ports: 
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30017
